version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Replace with the desired client port
 
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:8082
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:8082
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    networks:
      - kafka-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:8082
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
